### ISSUE TITLE
Some GR devices are missing

### ISSUE THREAD

**Issue by djacid** [gaetancollaud/digitalstrom-mqtt#17]
First of all, congratulations! Your code is awesome. I have sucessfully integrate Digitalstrom to Home Assistant via MQTT. The only problem that I have is that some GR devices are not published on MQTT and I really don't know the reason.

**Comment by gaetancollaud** [comment]
Thanks for the compliment.

Can you elaborate more, please? I developed this software with the devices that I have at home and have 
* GR-KL210
* GR-KL220

They work fine. They publish their position and angle (when available).

As described in the readme, there is no way to have an event for when a device output changes. So I listen to scene changes and update all the devices in the same room. So in order to publish the GR devices, you must trigger a scene in the same room (even responder will not work I guess).

**Comment by djacid** [comment]
I have 7 GR-KL200. Six of them are working perfectly. Only one was missing from mqtt. Firing an event was the solution. Thank you very much. Now I can see the device.
