### ISSUE TITLE
MQTT cannot fetch new values for groups

### ISSUE THREAD

**Issue by tchatziliadis** [gaetancollaud/digitalstrom-mqtt#24]
I have 2 problems.

1. I have created a group on digitalSTROM Configurator, with some lights and a push button. To be more specific, this group contains one input of a SW-TKM200 and 4 outputs of a GE-UMV200 (control of a RGBW ledstrip). So, whenever I push a wall button switch, the brightness of 4 outputs go to 100% or 0%. This works great! The problem is that mqtt cannot fetch these values. 

2. After the last updates of your code, I have problems with two of my covers. MQTT cannot fetch the new values by pressing the wall switch, but only for covers which are members of a group. 

So, I think that both of these two problems have a similarity, which is groups.

<img width="1792" alt="Screenshot 2022-01-23 at 12 59 24 PM" src="https://user-images.githubusercontent.com/94412007/150675325-50d26271-bef1-4dd6-b46f-82173f26b196.png">
<img width="1792" alt="Screenshot 2022-01-23 at 12 59 09 PM" src="https://user-images.githubusercontent.com/94412007/150675328-6b3fcb2b-8556-488c-9975-9ef151907c88.png">

**Comment by tchatziliadis** [comment]
It's definitely an issue related with groups, because I tried to create a room and not a group and it seems with rooms is working as it should.

**Comment by gaetancollaud** [comment]
Hello @tchatziliadis,

It's true that I check only for zone (room) updates (It's an optimization because asking for the state of a device is time-consuming, so I cannot refresh all the devices every time). But I should also look into groups. 

I will see if I have a bit of time this weekend to setup a group and try to make it work.

Thanks for the feedback.

**Comment by gaetancollaud** [comment]
Ok, sorry for the long delay. 
So I investigated a bit and it seems possible to retrieve the groups of each device. And when a group event is fired I could update the status of all the devices that are in this group. The issue is that I would have to refresh this information from time to time (in case you change the group in the config of digitalStrom). Because requesting it every time is way too costly.

I will see if I can come up with a solution.

**Comment by gaetancollaud** [comment]
@tchatziliadis I release the version `1.4.7` can you have a look please.
