### ISSUE TITLE
[HomeAssistant] Warning: Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by jtognazzi** [gaetancollaud/digitalstrom-mqtt#40]
Hi,
thanks for this project. It works very well.

I updated my server and notice this warning (see title and below) when restarting it.

> This stops working in version 2024.2.0. Please address before upgrading.
> Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

You are probably already informed. but if not now there is an issue about it.

**Comment by gaetancollaud** [comment]
Hello,

Thanks for reporting this.

I guess you are talking about home assistant ? I updated the title of the issue accordingly

I personally don't use HA so I'm not exactly sure what this issue is about. The HA implementation of this application was done by a contributor.

Will this break HA compatibility in the future ? I'm wondering since it's just a warning.

**Comment by jtognazzi** [comment]
Ah, ok

I guess this phrase:
> This stops working in version 2024.2.0. Please address before upgrading.

means it will stop working with the release in February 2024...

**Comment by gaetancollaud** [comment]
Ok, good to know. I'll investigate when I have time.

**Comment by gaetancollaud** [comment]
This will be fixed by 32c6ca8fa6ba7f330170a8fdd21abfe1520cbb4d once it's merged
