### ISSUE TITLE
"not logged in" after MQTT connection lost

### ISSUE THREAD

**Issue by dylancollaud** [gaetancollaud/digitalstrom-mqtt#8]
I saw in the log this error : 

`2021-04-14T19:06:06Z INF Error error="Error with digitalstrom API: not logged in" | stdout`

Printed 100 times per second at least.. 

The DSS Server has been updated last week and I thing this is linked. This app loose the credential to connect to the API.
The docker was buggy and the log did not display in Synology. I restarted the docker and the message disapeared.

Maybe in this case, don't try to log as this fast and maybe retry to get the credential.

**Comment by gaetancollaud** [comment]
Yeah it's true that I don't detect if the token is outdated... I just rely on the fact that I do a pooling every 30sec which extends the token indefinitely... 

Things to do: 
* Detect if the token is outdated
* Launch the http call again
* Maybe delay the retry otherwise we can end up in an infinite loop in case of upgrade

**Comment by gaetancollaud** [comment]
I got the error also. But it's not related to digitalSTROM, it's related to MQTT... When the MQTT server restarts I can also see those lines.

**Comment by gaetancollaud** [comment]
Closed by af62c786036b6a5b3c34de6668ea8e8c3575aa87
